'use client';
/* Native image elements preserve local object URLs and un-cropped photo-book layouts. */
/* eslint-disable @next/next/no-img-element */
import { useEffect, useRef, useState, type ChangeEvent, type DragEvent } from 'react';
import { usePathname, useRouter } from 'next/navigation';
import { ArrowUpRight, ArrowRight, ArrowLeft, X, ImagePlus, Check, Copy, RefreshCw, BookOpen, PenLine, Map, Feather, LockKeyhole } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PhotoGallery } from './PhotoGallery';
import { resultDisclosure } from '@/lib/story/style';
import { BRAND } from '@/lib/brand';
import { ReconstructionControl } from './ReconstructionControl';
import { QuestionPhotos } from './QuestionPhotos';
import { FictionOptions } from './FictionOptions';
import { fictionGenres } from '@/lib/story/formats';
import { ChapterOptions } from './ChapterOptions';
import { planChapters } from '@/lib/story/chapters';
import { Textarea } from '@/components/ui/textarea';
import { useStorySession } from '@/context/StorySessionContext';
import { demoPhotos, demoPhotoAnalysis, demoTimeline, demoQuestions, makeDemoStory } from '@/lib/demo/demoData';
import { preparePhoto, orderPhotos } from '@/lib/images/compress';
import { api } from '@/lib/api';
import { storyTypes, tones, type Analysis, type MissingContextQuestion, type GeneratedStory, type UploadedPhoto } from '@/types/story';
const privacy='업로드한 사진은 이야기 생성 및 분석 목적으로만 사용됩니다.';
const steps=['사진','기억','이야기'];
const icons=[PenLine,Map,Feather];
function Privacy(){return <p className="privacy"><LockKeyhole size={12}/>{privacy}</p>}
export function BetweenApp(){
 const {state,patch,reset}=useStorySession();const router=useRouter();const path=usePathname();
 const view=path==='/'?'landing':path.slice(1);
 function home(){reset();router.push('/');}
 function demo(){reset();patch({isDemo:true,uploadedPhotos:demoPhotos});router.push('/analysis');}
 const missing=view!=='landing'&&view!=='upload'&&state.uploadedPhotos.length===0;
 const invalid=!missing&&(['context','style'].includes(view)&&!state.analysis||view==='story'&&!state.generatedStory);
 return <><a className="skip-link" href="#main">본문으로 건너뛰기</a><header className="site-header"><button onClick={home} className="wordmark" aria-label={`${BRAND} 처음으로`}>{BRAND}</button>{view==='landing'?<span className="header-note">A LITTLE SPACE FOR YOUR MEMORIES</span>:<nav aria-label="이야기 만들기 단계" className="step-nav">{steps.map((s,i)=><span key={s} className={(view==='upload'||view==='analysis'?0:view==='context'?1:2)===i?'current':''}><small>0{i+1}</small> {s}{i<2&&<span className="step-line"/>}</span>)}</nav>}{view==='landing'?<Button variant="ghost" className="header-cta" onClick={()=>router.push('/upload')}>내 이야기 만들기 <ArrowUpRight size={15}/></Button>:<div className="header-end">{state.isDemo&&<span className="badge">DEMO</span>}<Button variant="ghost" size="icon" onClick={home} aria-label="현재 이야기 닫고 처음으로"><X size={18}/></Button></div>}</header>
 {missing||invalid?<main id="main" className="empty-page"><p className="eyebrow">A NEW BEGINNING</p><h1>새로운 이야기를 시작해볼까요?</h1><p>사진과 기억은 현재 페이지를 이용하는 동안만 보관됩니다.<br/>새로고침했다면 사진을 다시 선택해 주세요.</p><Button className="primary" onClick={()=>router.push('/upload')}>사진 선택하기 <ArrowRight/></Button><Button variant="ghost" onClick={demo}>샘플로 체험하기</Button></main>:view==='landing'?<Landing onStart={()=>router.push('/upload')} onDemo={demo}/>:view==='upload'?<Upload/>:view==='analysis'?<AnalysisScreen/>:view==='context'?<ContextScreen/>:view==='style'?<StyleScreen/>:view==='story'?<StoryScreen onHome={home}/>:null}
 <footer className="site-footer"><span><span className="brand-footer">{BRAND}</span><span className="footer-dot"> · </span>사진으로 남은 순간을, 글로 남깁니다.</span><span>MADE OF YOUR MOMENTS</span></footer></>;
}
function Landing({onStart,onDemo}:{onStart:()=>void;onDemo:()=>void}){return <main id="main"><section className="landing"><div className="hero-copy"><p className="eyebrow">PHOTOS → MEMORIES → WORDS</p><h1 className="scene-headline">사진으로 남은 순간을,<br/><em>글로 남깁니다.</em></h1><p className="hero-desc">여러 장의 사진과 당신의 기억을 AI가 하나의 글로 엮어요.<br/>질문에 답하지 않아도, 사진만으로 시작할 수 있어요.</p><div className="hero-actions"><Button className="primary" onClick={onStart}>내 이야기 만들기 <ArrowUpRight/></Button><Button variant="outline" className="secondary-button" onClick={onDemo}>샘플로 체험하기</Button></div><Privacy/></div><div className="hero-photos"><span className="photo-note">some days are worth keeping.</span><figure className="photo-main"><img src="/demo/photo-01.jpg" alt="옅은 하늘과 파도가 비치는 모래사장"/><figcaption>바다를 바라보던 어느 날</figcaption></figure><figure className="photo-small"><img src="/demo/photo-03.jpg" alt="나무 테이블 위에 놓인 커피 한 잔"/><figcaption>a little pause.</figcaption></figure><span className="vertical-caption">A COLLECTION OF LITTLE MOMENTS</span><div className="photo-caption"><span>A SCENE TO REMEMBER</span><span>01 — 03</span></div></div></section><section className="how-it-works" aria-label="이용 방법"><div className="section-kicker"><span>FROM MOMENTS TO WORDS</span><p>사진은 시작일 뿐,<br/>이야기는 그 사이에.</p></div>{['사진을 올려주세요.','기억을 조금 들려주세요.','하나의 이야기를 만나보세요.'].map((label,i)=><div className="how-step" key={label}><span className="step-number">0{i+1}</span><h2>{label}</h2><p>{['같은 날, 같은 여행, 간직하고 싶은 시간.','사진으로는 알 수 없는 당신만의 순간.','기록과 여행기, 상상으로 만든 소설까지.'][i]}</p></div>)}</section><div className="landing-bottom"><span>NO SIGN-UP. JUST YOUR MEMORIES.</span><a href="/demo/CREDITS.md" target="_blank" rel="noreferrer">Sample photography credits ↗</a></div></main>}
function Upload(){
 const {state,patch}=useStorySession();const router=useRouter();const input=useRef<HTMLInputElement>(null);const lock=useRef(false);
 const [busy,setBusy]=useState(false);const [errors,setErrors]=useState<string[]>([]);const [dragOver,setDragOver]=useState(false);const [dragged,setDragged]=useState<number|null>(null);
 async function addFiles(files:File[]){if(lock.current)return;lock.current=true;setBusy(true);const issues:string[]=[];const added:UploadedPhoto[]=[];const room=20-state.uploadedPhotos.length;
 if(files.length>room)issues.push('최대 20장까지 올릴 수 있어요. 초과한 사진은 추가하지 않았어요.');
 try{for(const file of files.slice(0,room)){try{added.push(await preparePhoto(file));}catch(error){issues.push(`${file.name}: ${error instanceof Error?error.message:'사진을 읽을 수 없어요.'}`);}}
 patch({chapterCount:null,uploadedPhotos:orderPhotos([...state.uploadedPhotos,...added],state.manuallyOrdered),analysis:null,generatedStory:null,contextQuestions:[],contextAnswers:[]});setErrors(issues);}finally{lock.current=false;setBusy(false);if(input.current)input.current.value='';}}
 function onChange(e:ChangeEvent<HTMLInputElement>){void addFiles(Array.from(e.target.files||[]));}
 function drop(e:DragEvent){e.preventDefault();setDragOver(false);if(e.dataTransfer.files.length)void addFiles(Array.from(e.dataTransfer.files));}
 function remove(i:number){const photo=state.uploadedPhotos[i];if(photo.src.startsWith('blob:'))URL.revokeObjectURL(photo.src);patch({chapterCount:null,uploadedPhotos:orderPhotos(state.uploadedPhotos.filter((_,j)=>j!==i),true),analysis:null,generatedStory:null});}
 function move(from:number,to:number){if(to<0||to>=state.uploadedPhotos.length||from===to)return;const list=[...state.uploadedPhotos];const [p]=list.splice(from,1);list.splice(to,0,p);patch({chapterCount:null,uploadedPhotos:orderPhotos(list,true),manuallyOrdered:true,analysis:null,generatedStory:null});setDragged(null);}
 return <main id="main" className="workspace upload-page"><div className="page-intro"><p className="eyebrow">CHAPTER 01 / YOUR PHOTOS</p><h1>어떤 시간을 기록해볼까요?</h1><p>같은 날, 여행 또는 하나의 기간에 찍은 사진을 선택해 주세요.</p></div><input ref={input} type="file" id="photo-upload" className="sr-only" aria-label="기억할 사진 선택" accept="image/jpeg,image/png,image/webp" multiple onChange={onChange} disabled={busy}/><button className={`dropzone ${dragOver?'drag-active':''} ${state.uploadedPhotos.length?'compact':''}`} onDragOver={e=>{e.preventDefault();setDragOver(true)}} onDragLeave={()=>setDragOver(false)} onDrop={drop} onClick={()=>input.current?.click()} disabled={busy||state.uploadedPhotos.length>=20}><span className="upload-icon"><ImagePlus strokeWidth={1.2} size={30}/></span><strong>{busy?'사진을 준비하고 있어요.':state.uploadedPhotos.length?'기억을 더 추가해 주세요.':'사진을 이곳에 놓아주세요.'}</strong><span>{busy?'사진 크기를 줄이고 촬영 정보를 살펴보고 있어요.':'또는 클릭해서 사진 선택하기'}</span><small>JPG, PNG, WEBP · 3–20장 · 사진당 최대 30MB</small></button>
 {errors.length>0&&<div className="error-note" role="alert">{errors.map((e,i)=><p key={i}>{e}</p>)}</div>}
 {state.uploadedPhotos.length>0&&<><div className="grid-label"><span>선택한 사진 <b>{state.uploadedPhotos.length}</b> / 20</span><span>드래그하거나 화살표로 순서를 바꿔보세요.</span></div><div className="thumbnail-grid">{state.uploadedPhotos.map((p,i)=><div key={p.id} className={`thumbnail ${dragged===i?'dragging':''}`} draggable={!busy} onDragStart={()=>setDragged(i)} onDragEnd={()=>setDragged(null)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();e.stopPropagation();if(dragged!==null)move(dragged,i);}}><img src={p.src} alt={`${i+1}번째 사진: ${p.name}`}/><span className="photo-index">{String(i+1).padStart(2,'0')}</span><button className="delete-photo" onClick={()=>remove(i)} disabled={busy} aria-label={`${i+1}번째 사진 삭제`}><X size={15}/></button><div className="reorder"><button onClick={()=>move(i,i-1)} disabled={i===0||busy} aria-label={`${i+1}번째 사진 앞으로 이동`}><ArrowLeft size={15}/></button><button onClick={()=>move(i,i+1)} disabled={i===state.uploadedPhotos.length-1||busy} aria-label={`${i+1}번째 사진 뒤로 이동`}><ArrowRight size={15}/></button></div></div>)}</div></>}
 <div className="upload-bottom"><div><Privacy/><p className="small-note">원본은 현재 브라우저에만 보관되며, 분석용 사본만 AI로 전달됩니다.</p></div><Button className="primary" disabled={state.uploadedPhotos.length<3||busy} onClick={()=>router.push('/analysis')}>사진 분석하기 <ArrowRight/></Button></div>{state.uploadedPhotos.length<3&&<p className="minimum-note">이야기를 만들려면 최소 3장의 사진이 필요해요.</p>}</main>;
}
function AnalysisScreen(){const [attempt,setAttempt]=useState(0);return <AnalysisRun key={attempt} retry={()=>setAttempt(a=>a+1)}/>;}
function AnalysisRun({retry}:{retry:()=>void}){
 const {state,patch}=useStorySession();const router=useRouter();const [phase,setPhase]=useState(0);const [error,setError]=useState('');const job=useRef<Promise<{analysis:Analysis;questions:MissingContextQuestion[]}>|null>(null);
 const messages=['사진을 살펴보고 있어요.','시간의 흐름을 찾고 있어요.','사진 사이의 장면을 연결하고 있어요.','조금 더 알고 싶은 것이 있어요.'];
 useEffect(()=>{const timer=setInterval(()=>setPhase(p=>Math.min(3,p+1)),state.isDemo?600:2800);return()=>clearInterval(timer);},[state.isDemo]);
 useEffect(()=>{
  let active=true;
  if(!job.current)job.current=(async()=>{if(state.isDemo){await new Promise(r=>setTimeout(r,2200));return {analysis:{photoAnalysis:demoPhotoAnalysis,timeline:demoTimeline},questions:demoQuestions};}
   let analysis=state.analysis;
   if(!analysis){const form=new FormData();form.append('metadata',JSON.stringify(state.uploadedPhotos.map(p=>({id:p.id,order:p.order,...(p.capturedAt?{capturedAt:p.capturedAt}:{})}))));for(const p of state.uploadedPhotos){if(!p.optimized)throw new Error('사진을 다시 선택해 주세요.');form.append('photos',p.optimized,'photo.jpg');}analysis=await api<Analysis>('/api/analyze',form);patch({analysis});}
   const result=await api<{questions:MissingContextQuestion[]}>('/api/questions',analysis);return {analysis,questions:result.questions};})();
  job.current.then(({analysis,questions})=>{if(!active)return;patch({analysis,contextQuestions:questions});router.replace(questions.length?'/context':'/style');}).catch(e=>{if(active)setError(e instanceof Error?e.message:'잠시 후 다시 시도해 주세요.');});
  return()=>{active=false;};
 },[state.isDemo,state.analysis,state.uploadedPhotos,patch,router]);
 return <main id="main" className="analysis-page"><p className="eyebrow">FINDING THE THREAD</p><div className="analysis-photos">{state.uploadedPhotos.slice(0,3).map((p,i)=><figure key={p.id} style={{animationDelay:`${i*.2}s`}}><img src={p.src} alt={`${i+1}번째 선택한 사진`}/></figure>)}</div>{error?<div className="analysis-message" role="alert"><h1>사진을 분석하는 중 문제가 발생했어요.</h1><p>{error}</p><div className="action-row"><Button className="primary" onClick={retry}>다시 시도 <RefreshCw/></Button><Button variant="ghost" onClick={()=>router.push('/upload')}>사진으로 돌아가기</Button></div></div>:<div className="analysis-message" aria-live="polite"><span className="loading-rule"/><h1 key={phase}>{messages[phase]}</h1><p>사진에 담긴 것과, 당신만 알고 있는 기억을 연결합니다.</p><div className="phase-dots" aria-hidden="true">{messages.map((_,i)=><span key={i} className={i<=phase?'active':''}/>)}</div>{state.isDemo&&<p className="small-note">샘플 사진으로 이야기의 과정을 체험하고 있어요.</p>}</div>}</main>;
}
function ContextScreen(){const {state,patch}=useStorySession();const router=useRouter();const [answers,setAnswers]=useState<Record<string,string>>(()=>Object.fromEntries(state.contextAnswers.map(a=>[a.questionId,a.answer])));
 return <main id="main" className="workspace context-page"><div className="page-intro"><p className="eyebrow">CHAPTER 02 / THE PART ONLY YOU KNOW</p><h1>사진만으로 알 수 없는 이야기를<br/>조금 알려주세요.</h1><p>사진의 양과 장면에 맞춰 {state.contextQuestions.length}개의 질문을 준비했어요. 답변은 모두 선택이에요.</p><p className="context-impact">들려주신 답변에 따라 글의 내용과 시선이 달라집니다. 꼭 남기고 싶은 장면이나 마음을 적어주세요.</p></div><div className="context-layout"><aside className="memory-strip">{state.uploadedPhotos.slice(0,3).map((p,i)=><figure key={p.id}><img src={p.src} alt={p.name}/><figcaption>0{i+1} / A MOMENT TO KEEP</figcaption></figure>)}<p>사진이 담지 못한<br/><em>당신만의 이야기.</em></p></aside><div className="questions">{state.contextQuestions.map((q,i)=><div className="question" key={q.id}><div className="question-label"><span>{String(i+1).padStart(2,'0')}</span><label htmlFor={q.id}>{q.question}</label></div><QuestionPhotos ids={q.photoIds??[]} photos={state.uploadedPhotos}/><Textarea id={q.id} maxLength={2000} value={answers[q.id]||''} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})} placeholder="기억나는 만큼 자유롭게 들려주세요." rows={3}/><span className="character-count">{(answers[q.id]||'').length} / 2,000</span></div>)}<div className="context-actions"><p className="small-note">답하기 어려운 질문은 비워 두어도 괜찮아요.</p><Button className="primary" onClick={()=>{patch({contextAnswers:state.contextQuestions.map(q=>({questionId:q.id,question:q.question,answer:answers[q.id]?.trim()||''}))});router.push('/style');}}>이 기억으로 이야기 만들기 <ArrowRight/></Button></div></div></div></main>;
}
function useGenerate(){const {state,patch}=useStorySession();const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const locked=useRef(false);const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 async function generate(){if(!state.analysis||locked.current)return;locked.current=true;setBusy(true);setError('');try{
 let story:GeneratedStory;
 if(state.isDemo){await new Promise(r=>setTimeout(r,900));story=makeDemoStory(state.storyType,state.writingTone,state.contextAnswers,state.demoRevision,state.letterDetails,state.storyType==='fiction'?100:state.creativity,planChapters(state.analysis,state.chapterCount),state.fictionGenre);}else story=await api<GeneratedStory>('/api/story',{...state.analysis,contextAnswers:state.contextAnswers,chapterCount:state.chapterCount,fictionGenre:state.fictionGenre,creativity:state.storyType==='fiction'?100:state.creativity,storyType:state.storyType,writingTone:state.writingTone});
 if(!mounted.current)return;patch({generatedStory:story,generatedCreativity:state.storyType==='fiction'?100:state.creativity,generatedFictionGenre:state.fictionGenre,generatedStoryType:state.storyType,generatedWritingTone:state.writingTone,demoRevision:state.demoRevision+1});router.push('/story');window.scrollTo({top:0,behavior:'smooth'});
 }catch(e){setError(e instanceof Error?e.message:'잠시 후 다시 시도해 주세요.');}finally{locked.current=false;setBusy(false);}}
 return {generate,busy,error};
}
function StyleScreen(){const {state,patch}=useStorySession();const router=useRouter();const {generate,busy,error}=useGenerate();
 return <main id="main" className="workspace style-page"><div className="page-intro"><p className="eyebrow">CHAPTER 03 / MAKE IT YOURS</p><h1>어떤 이야기로 남길까요?</h1><p>당신의 기억에 어울리는 형식과 문체를 골라보세요.</p></div><fieldset disabled={busy}><legend><span>01</span> 이야기의 형식</legend><div className="type-grid">{storyTypes.map((t,i)=>{const Icon=icons[i];return <label key={t.id} className={`type-card ${state.storyType===t.id?'selected':''}`}><input className="sr-only" type="radio" name="story-type" value={t.id} checked={state.storyType===t.id} onChange={()=>patch({storyType:t.id})}/><div className="type-top"><Icon size={23} strokeWidth={1.2}/><span className="selection-mark">{state.storyType===t.id&&<Check size={13}/>}</span></div><h2>{t.label}</h2><span className="type-en">{t.en}</span><p>{t.description}</p><small>{t.id==='fiction'?'STORY MODE':'MEMORY MODE'}</small></label>})}</div></fieldset><div className="mode-note">{state.storyType==='fiction'?<><Feather size={16}/><p>사진에서 소재를 얻어 장르에 맞는 짧은 단편소설을 창작합니다.</p></>:<><BookOpen size={16}/><p>사진과 직접 들려주신 기억을 바탕으로, 아래에서 고른 재구성 정도에 맞춰 씁니다.</p></>}</div>{state.storyType==='fiction'&&<FictionOptions disabled={busy}/>} <fieldset disabled={busy} className="tone-fieldset"><legend><span>02</span> 글의 분위기</legend><div className="tone-options">{tones.map(t=><label key={t.id} className={`tone-chip ${state.writingTone===t.id?'selected':''}`}><input type="radio" className="sr-only" name="tone" value={t.id} checked={state.writingTone===t.id} onChange={()=>patch({writingTone:t.id})}/>{state.writingTone===t.id&&<Check size={14}/>} {t.label}</label>)}</div><p className="small-note tone-description">{{plain:'수필처럼 구체적인 일상과 담담한 생각을 이어 씁니다.',emotional:'섬세한 순간과 절제된 감정으로 오래 남는 여운을 담습니다.',cinematic:'영화의 장면 전환과 나레이션처럼 리듬 있게 씁니다.',literary:'시처럼 선명한 이미지와 운율, 여백을 살립니다.',witty:'담백한 수필의 문체로 씁니다.'}[state.writingTone]}</p></fieldset>{state.storyType!=='fiction'&&<ReconstructionControl disabled={busy}/>}<ChapterOptions disabled={busy}/>{error&&<div className="error-note" role="alert"><strong>이야기를 만드는 중 문제가 발생했어요.</strong><p>{error}</p></div>}<div className="style-bottom"><Button variant="ghost" disabled={busy} onClick={()=>router.push(state.contextQuestions.length?'/context':'/upload')}><ArrowLeft/> 이전으로</Button><Button className="primary" disabled={busy} onClick={()=>void generate()}>{busy?'기억을 이야기로 엮고 있어요.':error?'다시 만들어보기':'이야기 만들기'}{busy?<span className="mini-spinner"/>:<ArrowRight/>}</Button></div>{busy&&<p className="generation-note" role="status">사진 사이의 순간을 문장으로 옮기고 있어요.</p>}</main>;
}
function StoryScreen({onHome}:{onHome:()=>void}){
 const {state}=useStorySession();const router=useRouter();const {generate,busy,error}=useGenerate();const [copyStatus,setCopyStatus]=useState('');const story=state.generatedStory!;
 const cover=state.uploadedPhotos.find(p=>p.id===story.coverPhotoId)||state.uploadedPhotos[0];const fiction=state.generatedStoryType==='fiction';const disclosure=resultDisclosure(state.generatedCreativity,fiction);
 const allDated=state.uploadedPhotos.every(p=>p.capturedAt);const dates=allDated?state.uploadedPhotos.map(p=>p.capturedAt!).sort():[];
 const dateText=dates.length?`${new Date(dates[0]).toLocaleDateString('ko-KR')} — ${new Date(dates.at(-1)!).toLocaleDateString('ko-KR')}`:'A MEMORY, KEPT IN WORDS';
 async function copy(){const text=[fiction?'STORY MODE':null,disclosure,story.title,story.subtitle,...story.sections.flatMap(s=>[s.heading,...s.paragraphs])].filter(Boolean).join('\n\n');try{await navigator.clipboard.writeText(text);setCopyStatus('글을 복사했어요.');}catch{setCopyStatus('복사 권한을 확인하거나 본문을 직접 선택해 주세요.');}}
 return <main id="main" className="story-page"><div className="story-title"><p className="eyebrow">{dateText}</p>{fiction&&<span className="badge fiction-badge">STORY MODE</span>}<h1>{story.title}</h1>{story.subtitle&&<p className="story-subtitle">{story.subtitle}</p>}<div className="story-meta"><span>{storyTypes.find(t=>t.id===state.generatedStoryType)?.label}</span><span>·</span><span>{tones.find(t=>t.id===state.generatedWritingTone)?.label}</span><span>·</span><span>{state.uploadedPhotos.length}장의 순간</span>{state.generatedStoryType==='fiction'&&<><span>·</span><span>{fictionGenres.find(g=>g.id===state.generatedFictionGenre)?.label}</span></>}</div>{disclosure&&<p className="fiction-disclaimer">{disclosure}</p>}</div><figure className="story-cover"><img src={cover.src} alt={`이야기의 대표 사진: ${cover.name}`}/><figcaption><span>{BRAND} / A PERSONAL COLLECTION</span><span>{state.isDemo?'SAMPLE STORY':'YOUR STORY'}</span></figcaption></figure><article className="story-body">{story.sections.map((section,i)=>{const photos=section.relatedPhotoIds.map(id=>state.uploadedPhotos.find(p=>p.id===id)).filter((p):p is UploadedPhoto=>!!p);return <section className="story-section" key={i}><div className="story-prose"><span className="chapter-number">{String(i+1).padStart(2,'0')}</span>{section.heading&&<h2>{section.heading}</h2>}{section.paragraphs.map((p,j)=><p key={j}>{p}</p>)}</div>{photos.length>0&&<PhotoGallery photos={photos}/>}</section>})}</article><div className="story-end"><span>—</span><p>사진과 사진 사이,<br/>당신의 이야기가 남았습니다.</p><span className="wordmark">{BRAND}</span></div>{error&&<div className="error-note" role="alert"><strong>이야기를 만드는 중 문제가 발생했어요.</strong><p>{error}</p></div>}<div className="result-actions"><Button variant="outline" onClick={()=>router.push('/style')} disabled={busy}><PenLine/> 문체 바꾸기</Button><Button variant="outline" onClick={()=>void generate()} disabled={busy}><RefreshCw className={busy?'spinning':''}/> {busy?'이야기를 엮고 있어요.':error?'다시 만들어보기':'다시 생성'}</Button><Button variant="outline" onClick={()=>void copy()}><Copy/> 글 복사</Button><Button variant="ghost" onClick={onHome} disabled={busy}>처음으로 <ArrowUpRight/></Button></div><p className="copy-status" role="status">{copyStatus|| (busy?'기억을 하나의 이야기로 엮고 있어요.':'')}</p></main>;
}
