import type {StoryType} from '@/types/story';
export const fictionGenres=[
 {id:'literary',label:'일상·문학',guide:'An everyday encounter that changes a character’s understanding; concrete tension and a earned, restrained ending.'},
 {id:'romance',label:'로맨스',guide:'Two distinct characters, an obstacle to connection, meaningful dialogue and a choice that changes their relationship.'},
 {id:'mystery',label:'미스터리',guide:'A concrete mystery about a disappearance, missing object or impossible event; visible clues, fair misdirection and a causally convincing reveal. No secret gratitude, surprise gift or friendship lesson as the main mystery.'},
 {id:'fantasy',label:'판타지',guide:'One clear impossible rule rooted in the photographed setting; a cost, a consequential choice, and resolution.'},
 {id:'sf',label:'SF',guide:'One speculative technology or future condition, its human consequence, a conflict and a satisfying resolution.'},
 {id:'healing',label:'힐링',guide:'A small concrete difficulty, supportive encounter and modest change; no generic inspirational speech or sudden miraculous cure.'},
] as const;
export type FictionGenre=typeof fictionGenres[number]['id'];
export const formatGuides:Record<StoryType,string>={
 record:`Write a broad personal record in the user's own voice. Experiences and memories supplied by the user lead the writing; visual details support them. Do not force a date, 오늘은 opening or end-of-day conclusion. Use natural Korean past tense and omitted first-person subjects. If there are no answers, build a connected passage using only confirmed surroundings, without pretending the narrator performed an unverified action; emotions and thoughts follow reconstruction permission. When there are answers, preserve their emotional nuance faithfully. Additional narrator feelings/thoughts follow reconstruction permission, but never invent personality history, dialogue, bodily sensations or anecdotes. Never invent the act of reviewing photos. Do not organize the prose as a slideshow. Do not manufacture a moral conclusion.`,
 essay:`Write an essay around one central question or thought arising from the user's supplied memory. Begin with a concrete experience, develop a line of reflection, and end with a changed or still-open thought. Visual details are supporting examples, not the paragraph structure. No tour through each image and no generic lesson; additional reflection follows reconstruction permission.`,
 travel:`Write the user's travel account around confirmed visits, encounters, incidents and impressions. Let details of place support the experience. Use only confirmed routes or transitions at every reconstruction level: image order never proves a return trip, arrival or departure. Avoid travel-brochure descriptions, photo inventories and slideshow transitions.`,
 letter:`Write directly to the recipient throughout: why these memories are being shared, a meaningful detail, and the actual message the user wants to convey. Do not turn the middle into detached photo captions or an essay to an anonymous reader. Keep salutation and signature at the beginning/end of the whole letter, not each chapter.`,
 fiction:`Write ONE complete original short story in the selected genre. Photographs provide setting, objects or motifs, not a sequence to describe. Invent fictional characters with a concrete desire, an obstacle, causally connected events, meaningful dialogue, a turning point and a resolved or deliberately resonant ending. Keep the same characters across chapters; no separate story per photo. Use photos selectively as story material while attaching the planned photos for display. Never identify fictional characters as real photographed people. Do not mention source images, the act of generating fiction, or explain symbolism to the reader. User memories are optional inspiration, not a factual constraint. Build an internal beginning-middle-end even when there is only one display chapter. Total prose should be at least 1200 Korean characters; for a single chapter aim for 1200–1800, for multiple chapters distribute the plot without repetitive openings or endings.`
};
export function needsFormatRevision(body:string){
 return /[}\]]{4,}|\}\s*\]\s*\}|이어지는 장면(에서|에서는|은)|(?:첫 번째|이어지는|마지막) 사진(?:에서|에서는|에는)|다음 (사진|프레임)(에서|에는|에서는)|사진 속에는|화면(의)? (오른쪽|왼쪽|중앙)|프레임 (안|속)|사진을 (펼쳐|살펴보면)|사진만으로는|서로 다른 시간처럼 놓여/.test(body);
}
